# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: example

---
apiVersion: v1
data:
  DBNAME: "sequelize"
  DBPASSWORD: "A020197kc"
  DBPORT: "5432"
  DBHOST: "18.210.20.38"
  DBUSER: "postgres"
  JWT_KEYS: "atiaKC"
  CLOUD_NAME: "devopsatia"
  CLOUD_API_KEY: "343976629857324"
  CLOUD_API_SECRET: "v-C70umdEJYOcwl8kdpkrfT-tq4"
  REDIS_HOST: "18.210.20.38"
  REDIS_PORT: "6379"
  SERVICEPORT: "9000"
  MODE: "Dev"

kind: ConfigMap
metadata:
  name: backendenv
  # namespace: example

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
        - name: k8s-backend
          image: atiakhairunican/jenkinsback:main
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: backendenv
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /api/product
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    tier: backend
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9000
      nodePort: 31284
      protocol: TCP
      name: backendport