apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontendapp
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontendapp
        tier: frontend
    spec:
      containers:
        - name: k8s-frontend
          image: atiakhairunican/jenkinsfront:main
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontendapp
    tier: frontend
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 31285
      protocol: TCP
      name: frontendport