apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: vuefront
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: vuefront
        tier: frontend
    spec:
      containers:
        - name: k8s-frontend
          image: atiakhairunican/jenkinsfront:main
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: vuefront
    tier: frontend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: frontendport