apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
        - name: k8s-backend
          image: atiakhairunican/jenkinsback:main
          ports:
            - containerPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: vuefront
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: vuefront
        tier: frontend
    spec:
      containers:
        - name: k8s-frontend
          image: atiakhairunican/jenkinsfront:main
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    tier: backend
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9000
      protocol: TCP
      name: backendport
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: vuefront
    tier: frontend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: frontendport