---
apiVersion: v1
kind: Namespace
metadata:
  name: example

---
apiVersion: v1
data:
  DBNAME: "sequelize"
  DBPASSWORD: "A020197kc"
  DBPORT: "5432"
  DBHOST: "localhost"
  DBUSER: "postgres"
  JWT_KEYS: "atiaKC"
  CLOUD_NAME: "devopsatia"
  CLOUD_API_KEY: "343976629857324"
  CLOUD_API_SECRET: "v-C70umdEJYOcwl8kdpkrfT-tq4"
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  SERVICEPORT: "9000"
  MODE: "Dev"

kind: ConfigMap
metadata:
  name: test-service
  namespace: example

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appbackend
  template:
    metadata:
      labels:
        app: appbackend
    spec:
      containers:
      - name: k8s-postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
      - name: k8s-redis
        image: redis:latest
        ports:
        - containerPort: 6379
      - name: k8s-backend
        image: atiakhairunican/jenkinsback:main
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: test-service

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: appbackend
  type: NodePort
  ports:
    - port: 5151
      targetPort: 5432
      nodePort: 31284
      protocol: TCP
      name: postgresservice
    - port: 6161
      targetPort: 6379
      nodePort: 31284
      protocol: TCP
      name: redisservice
    - port: 9191
      targetPort: 9000
      nodePort: 31284
      protocol: TCP
      name: backendservice